name: education_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^14.1.4
  mix: ^1.0.0
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  freezed: ^2.5.2
  riverpod_lint: ^2.3.10

flutter_gen:
  integrations:
    flutter_svg: true
  

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
